fix: Handle exception if generated SVG exceeds maximum string size. Log error and return empty SVG instead.
Upstream API for "https://github.com/vizdom-dev/vizdom" needs to be modified to expose a stream/buffer/byte[] interface.
Possible closed source.

Error: Cannot create a string longer than 0x1fffffe8 characters
    at TextDecoder.decode (node:internal/encoding:447:16)
    at getStringFromWasm0 (D:\Projects\NET\MISC\sbom-azure-devops\task\node_modules\@vizdom\vizdom-ts-node\vizdom_ts.js:22:30)
    at Svg.to_string (D:\Projects\NET\MISC\sbom-azure-devops\task\node_modules\@vizdom\vizdom-ts-node\vizdom_ts.js:1318:20)
    at D:\Projects\NET\MISC\sbom-azure-devops\task\utils\spdx\convertSpdxToSvg.ts:165:28
    at Generator.next (<anonymous>)
    at D:\Projects\NET\MISC\sbom-azure-devops\task\utils\spdx\convertSpdxToSvg.ts:41:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Projects\NET\MISC\sbom-azure-devops\task\utils\spdx\convertSpdxToSvg.ts:37:12)
    at convertSpdxToSvgAsync (D:\Projects\NET\MISC\sbom-azure-devops\task\utils\spdx\convertSpdxToSvg.ts:72:12)
    at SbomTool.<anonymous> (D:\Projects\NET\MISC\sbom-azure-devops\task\utils\sbomTool.ts:203:48) {
  code: 'ERR_STRING_TOO_LONG'